import type { Metadata } from "next";
import NextTopLoader from 'nextjs-toploader';
import { UserProvider } from '@/app/context/UserProvider'; // eller '@/app/_contexts/UserContext'
import { createClient } from '@/libs/supabase/client'
import "@/globals.css";

export const metadata: Metadata = {
  title: "Digital fabrikasjon platform",
  description: "Generated by create next app",
  authors: [
    { name: "Marianne Stavrum Myrvold" },
    { name: "Jennifer Grimsrud" }
  ],
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Opprett Supabase klient for server (med cookies)
  const supabase = createClient();

  // Hent autentisert bruker
  const { data: { user } } = await supabase.auth.getUser();

  let initialUser = null;

  // Hvis bruker er logget inn → hent ekstra info fra profiles-tabellen
  if (user) {
    const { data: profile } = await supabase
      .from('profiles')
      .select('role, full_name') // Legg gjerne til flere felter senere
      .eq('id', user.id)
      .single();

    initialUser = {
      id: user.id,
      email: user.email ?? null,
      role: profile?.role ?? 'user',
    };
  }

  return (
    <html lang="no">  {/* Endret til norsk */}
      <body className="antialiased">
        <NextTopLoader color="#3b82f6" />

        {/* UserProvider omslutter hele appen og får initial data fra server */}
        <UserProvider initialUser={initialUser}>
          {children}
        </UserProvider>

        <footer className="mt-auto p-4 text-center text-sm text-gray-600">
          <p className="font-mono">© 2025 Høgskolen i Østfold</p>
        </footer>
      </body>
    </html>
  );
}