import type { Metadata } from "next";
import { cookies } from 'next/headers'
import NextTopLoader from 'nextjs-toploader';
import { UserProvider } from '@/providers/UserProvider';
import { LanguageProvider, type Locale } from '@/providers/LanguageProvider';
import { createClient } from '@/lib/supabase/server'
import "@/globals.css";

export const metadata: Metadata = {
  title: "Digital fabrikasjon platform",
  description: "Generated by create next app",
  authors: [
    { name: "Marianne Stavrum Myrvold" },
    { name: "Jennifer Grimsrud" }
  ],
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Les språkinnstilling fra cookie
  const cookieStore = await cookies()
  const localeCookie = cookieStore.get('locale')?.value
  const initialLocale: Locale =
    localeCookie === 'en' || localeCookie === 'no' ? localeCookie : 'no'

  // Opprett Supabase klient for server (med cookies)
  const supabase = await createClient();

  // Hent autentisert bruker
  const { data: { user } } = await supabase.auth.getUser();

  let initialUser = null;

  // Hvis bruker er logget inn → hent ekstra info fra profiles-tabellen
  if (user) {
    const { data: profile } = await supabase
      .from('profiles')
      .select('role, assigned_to')
      .eq('id', user.id)
      .maybeSingle();

    initialUser = {
      id: user.id,
      email: user.email ?? null,
      role: profile?.role ?? 'user',
      assigned_to: profile?.assigned_to ?? null,
    };
  }

  return (
    <html lang={initialLocale}>
      <body className="antialiased">
        {/* WCAG 5.9 – Skip link */}
        <a href="#main-content" className="skip-link">
          {initialLocale === 'en' ? 'Skip to main content' : 'Hopp til hovedinnhold'}
        </a>

        <NextTopLoader color="#3b82f6" />

        <LanguageProvider initialLocale={initialLocale}>
          <UserProvider initialUser={initialUser}>
            {children}
          </UserProvider>
        </LanguageProvider>

        <footer className="mt-auto p-4 text-center text-sm text-gray-600">
          <p className="font-mono">© 2025 Høgskolen i Østfold</p>
        </footer>
      </body>
    </html>
  );
}